name: BuildIt
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: windows-2022
    steps:
    - name: "Clone source"
      uses: actions/checkout@v2
      with:
        submodules: 'true'
    - name: "Setup msvc"
      uses: ilammy/msvc-dev-cmd@v1
    - name: "Download Qt5"
      shell: bash
      run: |
        7z x -oC:/ "qt-5.15.0-static.zip.001"
    - name: "Build"
      run: |
        mkdir build
        cd build
        cmake -G "NMake Makefiles" "-DCMAKE_PREFIX_PATH:PATH=C:/qt-5.15.0-static" "-DCMAKE_MSVC_RUNTIME_LIBRARY:STRING=MultiThreaded" "-DCMAKE_BUILD_TYPE:STRING=Release" ..
        cmake --build .
    - name: "Package"
      shell: bash
      run: |
        ./make-release.sh build
        7z a cslol-manager-windows.zip cslol-manager/
    - name: 'Upload Artifact'
      uses: actions/upload-artifact@v2
      with:
        name: cslol-manager-windows
        path: cslol-manager-windows.zip
        retention-days: 15
